<template>
    <div>
        <scroll class="content">
        <ul>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
            <li>hell0</li>
        </ul>
    </scroll>
    </div>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll'
export default {
  name: 'Profile',
  components: {
    Scroll
  }
}
</script>

<style scoped>
.content {
    height: 300px;
    overflow: hidden;
}
</style>
